### ISSUE TITLE
Hotkey for activation

### ISSUE THREAD

**Issue by FlorianZahn** [trophygeek/universalvideomaximizer#10]
It would be cool to have a hot key to maxmize the window, e.g. ctrl +  space.

**Comment by trophygeek** [comment]
Someone else suggested this feature and it ends up it's built into chrome (just hard to find). See https://github.com/trophygeek/universalvideomaximizer/issues/8

**Comment by trophygeek** [comment]
Newest update includes a section in the Options page instructing how to set up Hotkeys in chrome.
