### ISSUE TITLE
"Use classic toggle zoom behavior" not working

### ISSUE THREAD

**Issue by Thomas-678** [trophygeek/universalvideomaximizer#5]
**Describe the bug**
I'm using the Beta v3 extension from chrome webstore. I right click on the extension icon, go into options, and turn on "Use classic toggle zoom behavior (will disable playback speed controls)". I expect when the video is in maximize mode, left clicking on the extension icon will exit maximize mode, but instead, it shows the playback speed menu. So I have to click twice to exit maximize mode.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 102.0.5005.63

**Comment by trophygeek** [comment]
Thanks for the report. Confirmed this bug.

I will investigate and fix. I also need to add a the extension's version number somewhere easy to get to so it can be included in bug reports.

**Comment by trophygeek** [comment]
Will be fixed in v3.0.54!

**Comment by trophygeek** [comment]
Fix is live on the Chrome Store.
