### ISSUE TITLE
[BUG] Zoom Selection Bar Persists Despite 'ADVANCED PLAYBACK FEATURES' Disabled

### ISSUE THREAD

**Issue by heltonricardo** [trophygeek/universalvideomaximizer#57]
**Describe the bug**

The issue I'm facing is that despite disabling the "ADVANCED PLAYBACK FEATURES" option, the zoom selection bar continues to appear. I want to use the tool solely to toggle zoom on and off without having to choose a zoom option.

**Expected behavior**
I expected that with the "ADVANCED PLAYBACK FEATURES" option disabled, I would only be able to toggle zoom on and off without the zoom selection bar appearing.

**Help Version info:**

- Chrome: Version 118.0.5993.70 (Official Build) (64-bit)
- OS: Microsoft Windows 10 Pro  Version 10.0.19045 Build 19045
- Extension: 3.0.112

**Comment by tomnielsen** [comment]
Thank you!

I introduced this bug in v3.0.112 when I removed the tutorial.

I have a one-line fix #56 and am waiting for the Chrome Store to approve and deploy it.

**Comment by trophygeek** [comment]
OK. It has been updated in the store finally.

**Comment by trophygeek** [comment]
Can you verify this is fixed for you? I don't want to close the issue until I get confirmation.

**Comment by heltonricardo** [comment]
I appreciate your prompt response and the quick fix. I've just updated the extension, and I can confirm that the issue is now resolved. Everything is working correctly as expected.

Thank you for your efforts in addressing this matter!

**Comment by heltonricardo** [comment]
Hello! Actually, I have encountered a problem on YouTube. When I click the extension icon once, the video does not maximize to full screen as expected. However, upon clicking the icon a second time, the zoom selection bar appears, even though I have "ADVANCED PLAYBACK FEATURES" disabled.

**Comment by trophygeek** [comment]
Does this only happen the first time or does it keep happening if you open a new browser window?

I think going from the broken version of VideoMax to the fixed version might require an extra click once or toggling the feature?

I'll do some more testing in Simple mode and see if I can reproduce this issue.

**Comment by heltonricardo** [comment]
I uninstalled the extension and then reinstalled it on Chrome. It now appears to be working correctly as intended. Thank you!!
