### ISSUE TITLE
Chat box maximised rather than video

### ISSUE THREAD

**Issue by Brleegb11** [trophygeek/universalvideomaximizer#59]
On Edge stable 11 pro sometimes get chat boxes maximised rather than video -  this on various streams from Footybite cant send link as streams only up for duration of a game. I can block the chatbox with ublock then works  fine again.
Otherwise works great.
Thanks

**Comment by trophygeek** [comment]
Do you have some specific URLs that I can use for testing?

**Comment by Brleegb11** [comment]
Will try to find one  is mostly working nice - ,may be just unlucky got a funny one x

**Comment by trophygeek** [comment]
OK. I'm going to close this bug for now.

I added Footybite to my list of tests. 

But let me know if you can find one particular video page that fails.
