### ISSUE TITLE
[BUG] Video detection fails when Disqus comment section is too large

### ISSUE THREAD

**Issue by Thomas-678** [trophygeek/universalvideomaximizer#6]
**Site not zooming**
URL to video (Site address): 
1. Not maximizing (Disqus comment section gets maximized): https://fmovies.to/series/narcos-mexico-yjjk0/1-1
2. Video maximized correctly: https://fmovies.to/series/broadchurch-026p5/1-1

FYI, launching chrome devtool on that site will bounce you back to homepage for some reason. For the first link above, I used uBlock Origin to remove Disqus from the webpage, and the video can then maximize.
Does site require a paid account? No

Extension version: 
Universal Video Maximizer BETA v3
v3.0.54 from chrome webstore

**Comment by trophygeek** [comment]
Sorry this took so long, but it should be fixed in 3.0.83.

**Comment by trophygeek** [comment]
Should be fixed.
