### ISSUE TITLE
video

### ISSUE THREAD

**Issue by DIENIS1** [trophygeek/universalvideomaximizer#63]
https://i.bgmicdn.com/images/chat/video/video.mp4

**Comment by trophygeek** [comment]
I guess this is to get my home IP address or show that you've correlated different github accounts?

I'm working on bugs for VideoMax, just check the `v3-typescript-cutover` branch. 

I've recently added support for shadowdom videos. Once I've got something that mostly works I'll be updating the VideoMax [beta channel](https://chromewebstore.google.com/detail/video-maximizer-beta/implccjhhblakjgebfhbafehkjjhklai?authuser=0&hl=en)
