### ISSUE TITLE
Create a Firefox compatible version based on v2 manifest

### ISSUE THREAD

**Issue by trophygeek** [trophygeek/universalvideomaximizer#7]
Chrome's v3 manifest/API is not currently supported by firefox. 

1. Create a branch based off v2 of the manifest
2. Build/test with firefox
3. Add to firefox specific extensions store
4. Profit! (kidding, it's free)

**Comment by trophygeek** [comment]
This is done. See FF extension store.

**Comment by heltonricardo** [comment]
Hello! I recommend adding the `_execute_browser_action` command to the **manifest.json** file in the Firefox version. This simple addition will enable users to define a command to maximize videos. For example:

```json
  "commands": {
    "_execute_browser_action": {
      "suggested_key": {
        "default": "Ctrl+Shift+V"
      },
      "description": "Maximize videos"
    }
  }
```

Thanks!
