### ISSUE TITLE
[BUG] No longer working on Chrome (106.0.5249.91) on Windows 10/6/2022

### ISSUE THREAD

**Issue by bonytony21** [trophygeek/universalvideomaximizer#9]
**Describe the bug**
Clicking on the Extension on a page with a video now no longer does anything. Video does not change. Extension Icon does not change to show the blue arrows to indicate it has maximized the video.

**To Reproduce**
1. Go to any site with a video, example youtube.com
2. Click on the extension.
3. See video doesn't expand and icon doesn't change.

INCLUDE SITE DETAILS:
- Which specific page is having the issue? Used on many video sites including youtube, behavior did not change.

**Expected behavior**
Video should expand to fill the tab, and the extension icon should show the blue side arrows.

**Version:**
Google Chrome | 106.0.5249.91 (Official Build) (64-bit) (cohort: Rampup_106)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 10 Version 21H1 (Build 19043.2006)
JavaScript | V8 10.6.194.17
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

 - Extension version. 2.0.20

**Comment by trophygeek** [comment]
Yikes. Thanks for reporting! I'll investigate.

In the meantime, can you try out the mv3 (Chrome's next extension API) beta?
https://chrome.google.com/webstore/detail/implccjhhblakjgebfhbafehkjjhklai?authuser=0&hl=en
